export const FETCH_POKEMONS_REQUEST = 'FETCH_POKEMONS_REQUEST' ;
export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS' ;
export const FETCH_POKEMONS_FAILURE = 'FETCH_POKEMONS_FAILURE' ;

export const FETCH_MORE_POKEMONS_REQUEST = 'FETCH_MORE_POKEMONS_REQUEST' ;
export const FETCH_MORE_POKEMONS_SUCCESS = 'FETCH_MORE_POKEMONS_SUCCESS' ;
export const FETCH_MORE_POKEMONS_FAILURE = 'FETCH_MORE_POKEMONS_FAILURE' ;


export const POKEAPI_URL = 'https://pokeapi.co/api/v2/pokemon';